In [1]:
import calendar
y=int(input("Enter a year :"))
m=int(input("Enter a month :"))
print(calendar.month(y,m))

Enter a year :2021
Enter a month :11
   November 2021
Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7
 8  9 10 11 12 13 14
15 16 17 18 19 20 21
22 23 24 25 26 27 28
29 30



In [2]:
import turtle
colors = ['red', 'purple', 'blue', 'green', 'orange', 'yellow']
t = turtle.Pen()
turtle.bgcolor('black')
for x in range(360):
    t.pencolor(colors[x%6])
    t.width(x//100 + 1)
    t.forward(x)
    t.left(59)

In [7]:
import turtle

a = turtle.Turtle()

for i in range(100):
    a.forward(5+i)
    a.right(15)

turtle.done()

TclError: invalid command name ".!canvas"

In [8]:
import turtle

a = turtle.Turtle()

for i in range(100):
    a.forward(5+i)
    a.right(15)

turtle.done()

Terminator: 

In [9]:
import pywhatkit as kit
import cv2

kit.text_to_handwriting("Hope you are doing well", save_to="handwriting.png")
img = cv2.imread("handwriting.png")
cv2.imshow("Text to Handwriting", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

ModuleNotFoundError: No module named 'pywhatkit'

In [17]:
import numpy as np
x = np.array([10,10,10,10,10,10])
y = np.array([9,9,9,9,9,9])
print("Original arrays:")
print(x)
print(y)
#result = np.sum((x == 10) & (y > .5))
#print("\nNumber of instances of a value occurring in one array on the condition of another array:")
#print(result)

Original arrays:
[10 10 10 10 10 10]
[9 9 9 9 9 9]


In [24]:
import numpy as np
a = [1, 1, 1 ,1, 1]
b = [5, 5, 5 ,5, 5]
ar1 = np.array(a)
ar2 = np.array(b)
print (ar1 + 1)
print (ar2 + 1)

[2 2 2 2 2]
[6 6 6 6 6]


In [25]:
import numpy as np
a = [5, 5, 5 ,5, 5]
b = [4, 4, 4 ,4, 4]
ar1 = np.array(a)
ar2 = np.array(b)
print (ar1 - 2)
print (ar2 - 2)

[3 3 3 3 3]
[2 2 2 2 2]


In [26]:
import numpy as np
a = [5, 5, 5 ,5, 5]
b = [4, 4, 4 ,4, 4]
ar1 = np.array(a)
ar2 = np.array(b)
print (ar1 +ar2)


[9 9 9 9 9]


In [28]:
import numpy as np
a = [5, 5, 5 ,5, 5]
b = [4, 4, 4 ,4, 4]
ar1 = np.array(a)
ar2 = np.array(b)
print (np.sum(ar1))


25
