In [1]:
import numpy as nup
array1=[]
r=int(input("Enter row size :"))
c=int(input("Enter column size :"))
for i in range(r):
    for j in range(c):
        array1.append(int(input("element:")))
array1=nup.array(array1).reshape(c,r)
print(array1)
array2=[]
r1=int(input("Enter row size :"))
c1=int(input("Enter column size :"))
for i in range(r1):
    for j in range(c1):
        array2.append(int(input("element:")))
array2=nup.array(array2).reshape(c1,r1)
print(array2)
print("dot product of two arrays are")
print(nup.dot(array1,array2))

Enter row size :2
Enter column size :2
element:2
element:2
element:2
element:2
[[2 2]
 [2 2]]
Enter row size :2
Enter column size :2
element:2
element:2
element:2
element:2
[[2 2]
 [2 2]]
dot product of two arrays are
[[8 8]
 [8 8]]
