In [2]:
import numpy as np
array1=[]
r=int(input("Enter row size :"))
c=int(input("Enter column size :"))
for i in range(r):
    for j in range(c):
        array1.append(int(input("element:")))
array1=np.array(array1).reshape(c,r)
print(array1)


array2=[]
r=int(input("Enter row size :"))
c=int(input("Enter column size :"))
for i in range(r):
    for j in range(c):
        array2.append(int(input("element:")))
array2=np.array(array2).reshape(c,r)
print(array2)

result1 =  np.linalg.inv(array1)
print("Inverse of the first array:")
print(result1)

result2 =  np.linalg.inv(array2)
print("Inverse of the second array:")
print(result2)


Enter row size :2
Enter column size :2
element:3
element:45
element:333
element:4
[[  3  45]
 [333   4]]
Enter row size :2
Enter column size :2
element:3
element:4
element:5
element:3
[[3 4]
 [5 3]]
Inverse of the first array:
[[-0.00026715  0.00300541]
 [ 0.02224003 -0.00020036]]
Inverse of the second array:
[[-0.27272727  0.36363636]
 [ 0.45454545 -0.27272727]]
